<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-09T16:30:10 IST" name="ECommerce Suite" finished-at="2025-02-09T16:32:08 IST" duration-ms="118107">
    <groups>
      <group name="e-Functional">
        <method signature="Purchaseordersuccess.Ordersubmit()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" name="Ordersubmit" class="seleniumframework.Tests.Purchaseordersuccess"/>
        <method signature="Purchaseordersuccess.productVerifyFail()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" name="productVerifyFail" class="seleniumframework.Tests.Purchaseordersuccess"/>
        <method signature="Purchaseordersuccess.verifyOrderPageForProduct()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" name="verifyOrderPageForProduct" class="seleniumframework.Tests.Purchaseordersuccess"/>
      </group> <!-- e-Functional -->
      <group name="login feature">
        <method signature="Errorlogin.errorLogin2(java.util.HashMap)[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" name="errorLogin2" class="seleniumframework.Tests.Errorlogin"/>
      </group> <!-- login feature -->
    </groups>
    <test started-at="2025-02-09T16:30:10 IST" name="product verify and order place Test" finished-at="2025-02-09T16:32:08 IST" duration-ms="118107">
      <class name="seleniumframework.Tests.Errorlogin">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:31:16 IST" name="launchApplication" finished-at="2025-02-09T16:31:44 IST" duration-ms="27820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorLogin2(java.util.HashMap)[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:31:44 IST" name="errorLogin2" data-provider="errorlogindata2" finished-at="2025-02-09T16:31:46 IST" duration-ms="1943" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Pizzoooasta@10, username=ajson.abdn@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorLogin2 -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:31:46 IST" name="closeApplication" finished-at="2025-02-09T16:31:46 IST" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:31:46 IST" name="launchApplication" finished-at="2025-02-09T16:32:06 IST" duration-ms="19542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorLogin2(java.util.HashMap)[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:32:06 IST" name="errorLogin2" data-provider="errorlogindata2" finished-at="2025-02-09T16:32:08 IST" duration-ms="2130" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Pjsonacho, username=amritha.upadhya@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorLogin2 -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumframework.Tests.Errorlogin@77888435]" started-at="2025-02-09T16:32:08 IST" name="closeApplication" finished-at="2025-02-09T16:32:08 IST" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- seleniumframework.Tests.Errorlogin -->
      <class name="seleniumframework.Tests.Purchaseordersuccess">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:11 IST" name="launchApplication" finished-at="2025-02-09T16:30:27 IST" duration-ms="16213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="Ordersubmit()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:27 IST" name="Ordersubmit" finished-at="2025-02-09T16:30:30 IST" duration-ms="3121" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at PageObjectdesigns.Purchasepage.addProductToCart(Purchasepage.java:60)
at seleniumframework.Tests.Purchaseordersuccess.Ordersubmit(Purchaseordersuccess.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Ordersubmit -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:30 IST" name="closeApplication" finished-at="2025-02-09T16:30:32 IST" duration-ms="1794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:32 IST" name="launchApplication" finished-at="2025-02-09T16:30:52 IST" duration-ms="20410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="Ordersubmit()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:52 IST" name="Ordersubmit" finished-at="2025-02-09T16:30:56 IST" duration-ms="4298" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at PageObjectdesigns.Purchasepage.addProductToCart(Purchasepage.java:60)
at seleniumframework.Tests.Purchaseordersuccess.Ordersubmit(Purchaseordersuccess.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Ordersubmit -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:57 IST" name="closeApplication" finished-at="2025-02-09T16:30:59 IST" duration-ms="1458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:30:59 IST" name="launchApplication" finished-at="2025-02-09T16:31:10 IST" duration-ms="11765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productVerifyFail()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:31:10 IST" name="productVerifyFail" finished-at="2025-02-09T16:31:14 IST" duration-ms="3278" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at PageObjectdesigns.Purchasepage.addProductToCart(Purchasepage.java:60)
at seleniumframework.Tests.Purchaseordersuccess.productVerifyFail(Purchaseordersuccess.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productVerifyFail -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:31:14 IST" name="closeApplication" finished-at="2025-02-09T16:31:14 IST" duration-ms="383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method signature="verifyOrderPageForProduct()[pri:0, instance:seleniumframework.Tests.Purchaseordersuccess@7d8995e]" started-at="2025-02-09T16:31:14 IST" name="verifyOrderPageForProduct" finished-at="2025-02-09T16:31:14 IST" depends-on-methods="seleniumframework.Tests.Purchaseordersuccess.Ordersubmit" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method seleniumframework.Tests.Purchaseordersuccess.verifyOrderPageForProduct() on instance seleniumframework.Tests.Purchaseordersuccess@7d8995e depends on not successfully finished methods 
[seleniumframework.Tests.Purchaseordersuccess.Ordersubmit() on instance seleniumframework.Tests.Purchaseordersuccess@7d8995e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method seleniumframework.Tests.Purchaseordersuccess.verifyOrderPageForProduct() on instance seleniumframework.Tests.Purchaseordersuccess@7d8995e depends on not successfully finished methods 
[seleniumframework.Tests.Purchaseordersuccess.Ordersubmit() on instance seleniumframework.Tests.Purchaseordersuccess@7d8995e]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderPageForProduct -->
      </class> <!-- seleniumframework.Tests.Purchaseordersuccess -->
    </test> <!-- product verify and order place Test -->
  </suite> <!-- ECommerce Suite -->
</testng-results>
